#!/usr/bin/env python3
import subprocess
from IPython import embed
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
#import matplotlib.cm as cm


def plot_global(df):
    sns.set()
    sns.set_context("talk")
    sns.lineplot(data=df, markers=[".", ".", "."], dashes=False)


    fit = np.linspace(0, len(df), len(df))**2
    plt.plot(df.index, fit, "--", color="lightgray")
    plt.annotate(r'$x^2$',  xy=(df.index[17], 320), xycoords='data', xytext=(-50, -60), textcoords='offset points', arrowprops=dict(arrowstyle='->', color='black', connectionstyle="angle3,angleA=90,angleB=0"))

    fit = np.linspace(0, len(df), len(df))**3
    plt.plot(df.index, fit, "--", color="lightgray")
    plt.annotate(r'$x^3$',  xy=(df.index[6], 280), xycoords='data', xytext=(-50, -60), textcoords='offset points', arrowprops=dict(arrowstyle='->', color='black', connectionstyle="angle3,angleA=90,angleB=0"))

    plt.title("Coronavirus en Argentina", fontsize=18)  # for title
    plt.xlabel("Fecha", fontsize=14)
    plt.ylabel("Casos", fontsize=14)
    plt.ylim(0, 700)
    plt.show()


if __name__ == "__main__":
    out = subprocess.call("./make_csv_from_md > arg.csv", shell=True)
    df = pd.read_csv("arg.csv")
    df = df.set_index(pd.to_datetime(df[['year', 'month', 'day']].apply(lambda x: "-".join((map(str,x.values))), axis=1) , format="%Y-%m-%d"))[['case', 'place', 'new']]
    acumulado = df.reset_index().groupby(['index', 'case']).sum().unstack().fillna(0).cumsum()
    acumulado.columns = acumulado.columns.droplevel()

    plot_global(acumulado)

    heat = df[df.case == 'CONFIRMADO'].reset_index().groupby(['index', 'place'])['new'].max().unstack()
    heat.index = heat.index.strftime("%d-%m")
    sns.heatmap(heat, annot=True, cbar=False, cmap='coolwarm', center=midpoint, annot_kws={'size':10})
    plt.ylabel("")
    plt.title("Confirmados por provincia")
    plt.show()
    #embed()
