#!/usr/bin/env python3

import os
from covid19.data_fetcher import download_files
import argparse
import glob
import pandas as pd
import sys


OUTPUT_DIR = "./data"
URL = "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data"  # JHU CCSE dataset


if __name__ == "__main__":
    #   parser = argparse.ArgumentParser(description="covid-pandanalysis")
    #   parser.add_argument("--fetch", action="store_true", help="Download data")
    #   args = parser.parse_args()

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        download_files(OUTPUT_DIR, URL)

    files = [OUTPUT_DIR+'/time_series_19-covid-Confirmed.csv', OUTPUT_DIR+'/time_series_19-covid-Deaths.csv', OUTPUT_DIR+'/time_series_19-covid-Recovered.csv']
    dfs = []
    for file in files:
        df = pd.read_csv(file).rename(columns={'Province/State':'state', 'Country/Region': 'country' }).drop(['Lat', 'Long'], axis=1)
        case = file.split('-')[-1][:-4]
        df['case'] = case
        index_columns = [df.country, df.state, df.case]
        index = list(zip(*index_columns))
        df.drop(['country', 'state', 'case'], axis=1, inplace=True)
        index_df = pd.MultiIndex.from_tuples(index, names=['country', 'state', 'case'])
        dfs.append(df.set_index(index_df))

    all_cases_df = pd.concat(dfs).T
    all_cases_df.set_index(pd.to_datetime(all_cases_df.index), inplace=True)
    df = all_cases_df.stack([1,0]).stack()
    idx_names = list(df.index.names)
    idx_names[0] = 'date'
    df.index.set_names(idx_names, inplace=True)

    from IPython import embed; embed()
