#!/usr/bin/env python3

import os
import argparse
import glob
import pandas as pd
import sys
import sh


DATA_REPO_URL = 'https://github.com/CSSEGISandData/COVID-19.git'
DATA_MASK = 'COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-%s.csv'
FILES = [DATA_MASK % s for s in ('Confirmed', 'Deaths', 'Recovered')]


if __name__ == "__main__":
    #   parser = argparse.ArgumentParser(description="covid-pandanalysis")
    #   parser.add_argument("--fetch", action="store_true", help="Download data")
    #   args = parser.parse_args()

    if not os.path.exists('COVID-19'):
        sh.git.clone(DATA_REPO_URL)
    sh.git.pull(_cwd='COVID-19')

    dfs = []
    for file in FILES:
        df = pd.read_csv(file).rename(columns={'Province/State':'state', 'Country/Region': 'country' }).drop(['Lat', 'Long'], axis=1)
        case = file.split('-')[-1][:-4]
        df['case'] = case
        index_columns = [df.country, df.state, df.case]
        index = list(zip(*index_columns))
        df.drop(['country', 'state', 'case'], axis=1, inplace=True)
        index_df = pd.MultiIndex.from_tuples(index, names=['country', 'state', 'case'])
        dfs.append(df.set_index(index_df))

    all_cases_df = pd.concat(dfs).T
    all_cases_df.set_index(pd.to_datetime(all_cases_df.index), inplace=True)
    df = all_cases_df.stack([1,0]).stack()
    idx_names = list(df.index.names)
    idx_names[0] = 'date'
    df.index.set_names(idx_names, inplace=True)

    from IPython import embed; embed()
